coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
# Updated 20251109_123817
# Updated Sun Nov  9 12:49:51 CET 2025
# Updated Sun Nov  9 12:52:27 CET 2025
